const { pool }=require('../config/database');
function http(status,message){const e=new Error(message);e.status=status;return e;}
async function mark(d,user){
 const [t]=await pool.execute('SELECT teacher_id FROM teachers WHERE user_id=?',[user.user_id]);if(!t.length)throw http(403,'Teacher profile required');
 const teacherId=t[0].teacher_id; if(user.role_name==='teacher'){const [own]=await pool.execute('SELECT section_id FROM sections WHERE section_id=? AND class_teacher_id=?',[d.section_id,teacherId]);if(!own.length){const [a]=await pool.execute('SELECT 1 FROM teacher_subject_assignments WHERE teacher_id=? AND section_id=? LIMIT 1',[teacherId,d.section_id]);if(!a.length)throw http(403,'You are not assigned to this section');}}
 const [sec]=await pool.execute('SELECT section_id FROM sections WHERE section_id=?',[d.section_id]);if(!sec.length)throw http(404,'Section not found');
 const conn=await pool.getConnection();try{await conn.beginTransaction();const out=[];for(const x of d.records){const [st]=await conn.execute('SELECT student_id FROM students WHERE student_id=? AND section_id=?',[x.student_id,d.section_id]);if(!st.length)throw http(400,`Student ${x.student_id} does not belong to this section`);await conn.execute(`INSERT INTO attendance(student_id,section_id,marked_by,attendance_date,status,remarks) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE section_id=VALUES(section_id),marked_by=VALUES(marked_by),status=VALUES(status),remarks=VALUES(remarks)`,[x.student_id,d.section_id,teacherId,d.attendance_date,x.status,x.remarks??null]);const[r]=await conn.execute('SELECT * FROM attendance WHERE student_id=? AND attendance_date=?',[x.student_id,d.attendance_date]);out.push(r[0]);}await conn.commit();return out;}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function list(q){let sql='SELECT * FROM attendance WHERE 1=1',p=[];for(const [k,col] of [['student_id','student_id'],['section_id','section_id'],['marked_by','marked_by'],['status','status'],['attendance_date','attendance_date']])if(q[k]!=null){sql+=` AND ${col}=?`;p.push(q[k]);}if(q.from_date){sql+=' AND attendance_date>=?';p.push(q.from_date);}if(q.to_date){sql+=' AND attendance_date<=?';p.push(q.to_date);}sql+=' ORDER BY attendance_date DESC,attendance_id DESC LIMIT ? OFFSET ?';p.push(Number(q.limit??100),Number(q.skip??0));const[r]=await pool.execute(sql,p);return r;}
async function daily(date,sectionId){return list({attendance_date:date,section_id:sectionId,limit:10000,skip:0});}async function range(from,to,sectionId){return list({from_date:from,to_date:to,section_id:sectionId,limit:10000,skip:0});}
async function summary(studentId){const[r]=await pool.execute(`SELECT COUNT(*) total_days,SUM(status='present') present_days,SUM(status='absent') absent_days,SUM(status='late') late_days,SUM(status='leave') leave_days FROM attendance WHERE student_id=?`,[studentId]);const x=r[0];const total=Number(x.total_days||0);return {total_days:total,present_days:Number(x.present_days||0),absent_days:Number(x.absent_days||0),late_days:Number(x.late_days||0),leave_days:Number(x.leave_days||0),percentage:total?Number((((Number(x.present_days||0)+Number(x.late_days||0))/total)*100).toFixed(2)):0};}
async function update(id,d,user){const[t]=await pool.execute('SELECT teacher_id FROM teachers WHERE user_id=?',[user.user_id]);if(!t.length)throw http(403,'Teacher profile required');const fields=[],p=[];if(d.status!==undefined)fields.push('status=?'),p.push(d.status);if(d.remarks!==undefined)fields.push('remarks=?'),p.push(d.remarks);if(!fields.length)return get(id);p.push(id);const[r]=await pool.execute(`UPDATE attendance SET ${fields.join(',')} WHERE attendance_id=?`,p);if(!r.affectedRows)throw http(404,'Attendance not found');return get(id);}async function get(id){const[r]=await pool.execute('SELECT * FROM attendance WHERE attendance_id=?',[id]);return r[0]||null;}async function remove(id){const[r]=await pool.execute('DELETE FROM attendance WHERE attendance_id=?',[id]);if(!r.affectedRows)throw http(404,'Attendance not found');}
module.exports={mark,list,daily,range,summary,update,get,remove};
