const {pool}=require('../config/database');
const today=()=>new Date().toISOString().slice(0,10);
const notFound=m=>Object.assign(new Error(m),{status:404});
async function createFeeStructure(d){const [r]=await pool.execute('INSERT INTO fee_structures (class_id,fee_title,amount,frequency) VALUES (?,?,?,?)',[d.class_id,d.fee_title,d.amount,d.frequency]);return getFeeStructure(r.insertId);}
async function listFeeStructures(classId){let q='SELECT fee_structure_id,class_id,fee_title,amount,frequency FROM fee_structures',p=[];if(classId!==undefined&&classId!==null){q+=' WHERE class_id=?';p.push(Number(classId));}q+=' ORDER BY fee_structure_id ASC';const [r]=await pool.execute(q,p);return r;}
async function getFeeStructure(id){const [r]=await pool.execute('SELECT fee_structure_id,class_id,fee_title,amount,frequency FROM fee_structures WHERE fee_structure_id=?',[id]);return r[0]||null;}
async function updateFeeStructure(id,d){if(!await getFeeStructure(id))throw notFound('Fee structure not found');const fs=['fee_title','amount','frequency'],f=[],p=[];for(const k of fs)if(Object.hasOwn(d,k)){f.push(`${k}=?`);p.push(d[k]);}if(f.length){p.push(id);try{await pool.execute(`UPDATE fee_structures SET ${f.join(', ')} WHERE fee_structure_id=?`,p);}catch(e){if(e.code==='ER_ROW_IS_REFERENCED_2'){const x=Object.assign(new Error('Cannot update fee structure'),{status:409});throw x;}throw e;}}return getFeeStructure(id);}
async function deleteFeeStructure(id){if(!await getFeeStructure(id))throw notFound('Fee structure not found');try{await pool.execute('DELETE FROM fee_structures WHERE fee_structure_id=?',[id]);}catch(e){if(e.code==='ER_ROW_IS_REFERENCED_2'||e.code==='ER_ROW_IS_REFERENCED'){throw Object.assign(new Error('Cannot delete: challans already exist against this fee structure'),{status:409});}throw e;}}
async function nextChallanNo(conn){const prefix=`CH-${today().slice(0,7).replace('-','')}-`;const [r]=await conn.execute('SELECT COUNT(*) c FROM fee_challans WHERE challan_no LIKE ?',[`${prefix}%`]);return `${prefix}${String(Number(r[0].c)+1).padStart(5,'0')}`;}
async function notify(userId,title,message,type,referenceId=null,conn=pool){if(!userId)return;await conn.execute('INSERT INTO notifications (user_id,title,message,type,reference_id) VALUES (?,?,?,?,?)',[userId,title,message,type,referenceId]);}
async function notifyMany(userIds,title,message,type,conn=pool){if(!userIds.length)return;for(const id of userIds)await notify(id,title,message,type,null,conn);}
async function generateForStudent(d){const [s]=await pool.execute('SELECT student_id,user_id FROM students WHERE student_id=?',[d.student_id]);if(!s.length)throw notFound('Student not found');const structure=await getFeeStructure(d.fee_structure_id);if(!structure)throw notFound('Fee structure not found');const conn=await pool.getConnection();try{await conn.beginTransaction();const no=await nextChallanNo(conn);const [r]=await conn.execute('INSERT INTO fee_challans (student_id,fee_structure_id,challan_no,month_year,amount,fine_amount,due_date,status) VALUES (?,?,?,?,?,?,?,?)',[d.student_id,d.fee_structure_id,no,d.month_year,structure.amount,d.fine_amount,d.due_date,'unpaid']);await notify(s[0].user_id,`Fee Challan Generated: ${structure.fee_title}`,`Amount due: ${structure.amount} by ${d.due_date}`,'fee',r.insertId,conn);await conn.commit();return getChallan(r.insertId);}catch(e){await conn.rollback();if(e.code==='ER_DUP_ENTRY')throw Object.assign(new Error('A challan with this number already exists — please retry'),{status:409});throw e;}finally{conn.release();}}
async function generateForClass(d){const structure=await getFeeStructure(d.fee_structure_id);if(!structure)throw notFound('Fee structure not found');const [students]=await pool.execute("SELECT student_id,user_id FROM students WHERE section_id=? AND status='active'",[d.section_id]);if(!students.length)throw notFound('No active students found in this section');const conn=await pool.getConnection();const out=[];try{await conn.beginTransaction();for(const s of students){const no=await nextChallanNo(conn);const [r]=await conn.execute('INSERT INTO fee_challans (student_id,fee_structure_id,challan_no,month_year,amount,fine_amount,due_date,status) VALUES (?,?,?,?,?,?,?,?)',[s.student_id,d.fee_structure_id,no,d.month_year,structure.amount,0,d.due_date,'unpaid']);out.push(r.insertId);}for(const s of students)await notify(s.user_id,`Fee Challan Generated: ${structure.fee_title}`,`Amount due: ${structure.amount} by ${d.due_date}`,'fee',null,conn);await conn.commit();const [rows]=await pool.query(`SELECT challan_id,student_id,fee_structure_id,challan_no,month_year,amount,fine_amount,due_date,paid_date,status,payment_method FROM fee_challans WHERE challan_id IN (${out.map(()=>'?').join(',')})`,out);return out.map(id=>rows.find(x=>Number(x.challan_id)===Number(id)));}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function markOverdue(rows){const t=today();const ids=rows.filter(x=>x.status==='unpaid'&&String(x.due_date).slice(0,10)<t).map(x=>x.challan_id);if(ids.length)await pool.query(`UPDATE fee_challans SET status='overdue' WHERE challan_id IN (${ids.map(()=>'?').join(',')})`,ids);return ids.length;}
async function listChallans({studentId,status,monthYear,skip=0,limit=200}){let q='SELECT challan_id,student_id,fee_structure_id,challan_no,month_year,amount,fine_amount,due_date,paid_date,status,payment_method FROM fee_challans WHERE 1=1',p=[];if(studentId!==undefined&&studentId!==null){q+=' AND student_id=?';p.push(Number(studentId));}if(status){q+=' AND status=?';p.push(status);}if(monthYear){q+=' AND month_year=?';p.push(monthYear);}const [all]=await pool.execute(q,p);await markOverdue(all);q+=' ORDER BY due_date DESC LIMIT ? OFFSET ?';p.push(Number(limit),Number(skip));const [r]=await pool.execute(q,p);return r;}
async function getChallan(id){const [r]=await pool.execute('SELECT challan_id,student_id,fee_structure_id,challan_no,month_year,amount,fine_amount,due_date,paid_date,status,payment_method FROM fee_challans WHERE challan_id=?',[id]);if(!r.length)throw notFound('Fee challan not found');const c=r[0];if(c.status==='unpaid'&&String(c.due_date).slice(0,10)<today()){await pool.execute("UPDATE fee_challans SET status='overdue' WHERE challan_id=?",[id]);c.status='overdue';}return c;}
async function payChallan(id,d){const c=await getChallan(id);if(c.status==='paid')throw Object.assign(new Error('This challan has already been paid'),{status:400});if(c.status==='cancelled')throw Object.assign(new Error('This challan has been cancelled and cannot be paid'),{status:400});await pool.execute('UPDATE fee_challans SET status=?,payment_method=?,paid_date=? WHERE challan_id=?',['paid',d.payment_method,d.paid_date||today(),id]);return getChallan(id);}
async function updateChallan(id,d){await getChallan(id);const f=[],p=[];for(const k of ['due_date','fine_amount','status'])if(Object.hasOwn(d,k)){f.push(`${k}=?`);p.push(d[k]);}if(f.length){p.push(id);await pool.execute(`UPDATE fee_challans SET ${f.join(', ')} WHERE challan_id=?`,p);}return getChallan(id);}
async function deleteChallan(id){await getChallan(id);await pool.execute('DELETE FROM fee_challans WHERE challan_id=?',[id]);}
async function summary(monthYear){let q='SELECT challan_id,amount,fine_amount,due_date,status FROM fee_challans',p=[];if(monthYear){q+=' WHERE month_year=?';p.push(monthYear);}const [rows]=await pool.execute(q,p);await markOverdue(rows);if(rows.some(x=>x.status==='unpaid'&&String(x.due_date).slice(0,10)<today())){const [fresh]=await pool.execute(q,p);rows.splice(0,rows.length,...fresh);}const total=(rows.reduce((a,c)=>a+Number(c.amount)+Number(c.fine_amount||0),0));const collected=rows.filter(c=>c.status==='paid').reduce((a,c)=>a+Number(c.amount)+Number(c.fine_amount||0),0);return {total_challans:rows.length,total_amount_billed:total,total_amount_collected:collected,total_amount_pending:total-collected,paid_count:rows.filter(c=>c.status==='paid').length,unpaid_count:rows.filter(c=>c.status==='unpaid').length,overdue_count:rows.filter(c=>c.status==='overdue').length};}
module.exports={createFeeStructure,listFeeStructures,getFeeStructure,updateFeeStructure,deleteFeeStructure,generateForStudent,generateForClass,listChallans,getChallan,payChallan,updateChallan,deleteChallan,summary};
