const {pool}=require('../config/database');const nf=m=>Object.assign(new Error(m),{status:404});
async function create(d,teacherId){if(String(d.due_date)<String(d.assigned_date))throw Object.assign(new Error('due_date cannot be before assigned_date'),{status:400});const [r]=await pool.execute('INSERT INTO homework (section_id,subject_id,teacher_id,title,description,attachment_path,assigned_date,due_date) VALUES (?,?,?,?,?,?,?,?)',[d.section_id,d.subject_id,teacherId,d.title,d.description,d.attachment_path,d.assigned_date,d.due_date]);const out=await get(r.insertId);const [users]=await pool.execute('SELECT user_id FROM students WHERE section_id=?',[d.section_id]);for(const u of users)await pool.execute('INSERT INTO notifications (user_id,title,message,type,reference_id) VALUES (?,?,?,?,?)',[u.user_id,`New Homework: ${out.title}`,`Due on ${out.due_date}`,'homework',out.homework_id]);return out;}
async function list({sectionId,subjectId,teacherId,skip=0,limit=100}){let q='SELECT homework_id,section_id,subject_id,teacher_id,title,description,attachment_path,assigned_date,due_date FROM homework WHERE 1=1',p=[];for(const [col,val] of [['section_id',sectionId],['subject_id',subjectId],['teacher_id',teacherId]])if(val!==undefined&&val!==null){q+=` AND ${col}=?`;p.push(Number(val));}q+=' ORDER BY due_date DESC LIMIT ? OFFSET ?';p.push(Number(limit),Number(skip));const [r]=await pool.execute(q,p);return r;}
async function get(id){const [r]=await pool.execute('SELECT homework_id,section_id,subject_id,teacher_id,title,description,attachment_path,assigned_date,due_date FROM homework WHERE homework_id=?',[id]);return r[0]||null;}
async function update(id,d,teacherId){const o=await get(id);if(!o)throw nf('Homework not found');if(Number(o.teacher_id)!==Number(teacherId))throw Object.assign(new Error('You can only edit homework you assigned'),{status:403});const merged={...o,...d};if(String(merged.due_date)<String(merged.assigned_date))throw Object.assign(new Error('due_date cannot be before assigned_date'),{status:400});const f=[],p=[];for(const k of ['title','description','attachment_path','due_date'])if(Object.hasOwn(d,k)){f.push(`${k}=?`);p.push(d[k]);}if(f.length){p.push(id);await pool.execute(`UPDATE homework SET ${f.join(', ')} WHERE homework_id=?`,p);}return get(id);}
async function del(id,teacherId){const o=await get(id);if(!o)throw nf('Homework not found');if(Number(o.teacher_id)!==Number(teacherId))throw Object.assign(new Error('You can only delete homework you assigned'),{status:403});await pool.execute('DELETE FROM homework WHERE homework_id=?',[id]);}
async function submit(id,studentId,filePath){const h=await get(id);if(!h)throw nf('Homework not found');const late=new Date().toISOString().slice(0,10)>String(h.due_date).slice(0,10);const status=late?'late':'submitted';const [x]=await pool.execute('SELECT submission_id FROM homework_submissions WHERE homework_id=? AND student_id=?',[id,studentId]);if(x.length){await pool.execute('UPDATE homework_submissions SET file_path=?,status=?,submitted_at=CURRENT_TIMESTAMP WHERE submission_id=?',[filePath,status,x[0].submission_id]);return getSubmission(x[0].submission_id);}const [r]=await pool.execute('INSERT INTO homework_submissions (homework_id,student_id,file_path,status) VALUES (?,?,?,?)',[id,studentId,filePath,status]);return getSubmission(r.insertId);}
async function submissions(id){if(!await get(id))throw nf('Homework not found');const [r]=await pool.execute('SELECT submission_id,homework_id,student_id,file_path,submitted_at,status,grade_remarks FROM homework_submissions WHERE homework_id=?',[id]);return r;}
async function getSubmission(id){const [r]=await pool.execute('SELECT submission_id,homework_id,student_id,file_path,submitted_at,status,grade_remarks FROM homework_submissions WHERE submission_id=?',[id]);return r[0]||null;}
async function grade(id,remarks){const x=await getSubmission(id);if(!x)throw nf('Submission not found');await pool.execute("UPDATE homework_submissions SET grade_remarks=?,status='graded' WHERE submission_id=?",[remarks,id]);return getSubmission(id);}
async function teacherByUser(userId){const [r]=await pool.execute('SELECT teacher_id FROM teachers WHERE user_id=?',[userId]);return r[0]||null;}async function studentByUser(userId){const [r]=await pool.execute('SELECT student_id FROM students WHERE user_id=?',[userId]);return r[0]||null;}
module.exports={create,list,get,update,del,submit,submissions,grade,teacherByUser,studentByUser};
