const {pool}=require('../config/database');
const n=require('./notification.service');
const nf=m=>Object.assign(new Error(m),{status:404});
const validAudience=new Set(['all','teachers','students','parents','specific_class']);
async function audienceUsers(audience,classId){
 if(audience==='teachers'){const [r]=await pool.execute('SELECT user_id FROM teachers');return r.map(x=>x.user_id);}
 if(audience==='students'){const [r]=await pool.execute('SELECT user_id FROM students');return r.map(x=>x.user_id);}
 if(audience==='parents'){const [r]=await pool.execute('SELECT user_id FROM parents');return r.map(x=>x.user_id);}
 if(audience==='specific_class'){if(classId==null)return [];const [r]=await pool.execute('SELECT s.user_id FROM students s JOIN sections sec ON sec.section_id=s.section_id WHERE sec.class_id=?',[classId]);return r.map(x=>x.user_id);}
 const [r]=await pool.execute('SELECT user_id FROM users');return r.map(x=>x.user_id);
}
async function create(d,postedBy){if(!validAudience.has(d.audience))throw Object.assign(new Error('Invalid audience'),{status:400});if(d.audience==='specific_class'&&d.class_id==null)throw Object.assign(new Error("class_id is required when audience is 'specific_class'"),{status:400});if(d.expiry_date&&String(d.expiry_date)<String(d.publish_date))throw Object.assign(new Error('expiry_date cannot be before publish_date'),{status:400});const [r]=await pool.execute('INSERT INTO notices (title,description,posted_by,audience,class_id,attachment_path,publish_date,expiry_date) VALUES (?,?,?,?,?,?,?,?)',[d.title,d.description??null,postedBy,d.audience,d.class_id??null,d.attachment_path??null,d.publish_date,d.expiry_date??null]);const out=await get(r.insertId);const ids=await audienceUsers(d.audience,d.class_id);await n.createNotificationsBulk(ids,`New Notice: ${out.title}`,(out.description||'').slice(0,500),'notice',out.notice_id);return out;}
async function list({audience,classId,activeOnly=true,skip=0,limit=100}){let q='SELECT notice_id,title,description,posted_by,audience,class_id,attachment_path,publish_date,expiry_date FROM notices WHERE 1=1',p=[];if(audience){q+=' AND audience=?';p.push(audience);}if(classId!=null){q+=' AND class_id=?';p.push(Number(classId));}if(activeOnly){q+=' AND publish_date<=CURDATE() AND (expiry_date IS NULL OR expiry_date>=CURDATE())';}q+=' ORDER BY publish_date DESC LIMIT ? OFFSET ?';p.push(Number(limit),Number(skip));const [r]=await pool.execute(q,p);return r;}
async function listForUser(user,skip=0,limit=100){let q='SELECT notice_id,title,description,posted_by,audience,class_id,attachment_path,publish_date,expiry_date FROM notices WHERE publish_date<=CURDATE() AND (expiry_date IS NULL OR expiry_date>=CURDATE())',p=[];if(user.role_name==='student'){const [s]=await pool.execute('SELECT sec.class_id FROM students st JOIN sections sec ON sec.section_id=st.section_id WHERE st.user_id=?',[user.user_id]);const cid=s[0]?.class_id??null;q+=' AND (audience IN (\'all\',\'students\') OR (audience=\'specific_class\' AND class_id=?))';p.push(cid);}else if(user.role_name==='teacher')q+=" AND audience IN ('all','teachers')";else if(user.role_name==='parent')q+=" AND audience IN ('all','parents')";q+=' ORDER BY publish_date DESC LIMIT ? OFFSET ?';p.push(Number(limit),Number(skip));const [r]=await pool.execute(q,p);return r;}
async function get(id){const [r]=await pool.execute('SELECT notice_id,title,description,posted_by,audience,class_id,attachment_path,publish_date,expiry_date FROM notices WHERE notice_id=?',[id]);return r[0]||null;}
async function update(id,d){if(!await get(id))throw nf('Notice not found');if(d.expiry_date&&d.publish_date&&String(d.expiry_date)<String(d.publish_date))throw Object.assign(new Error('expiry_date cannot be before publish_date'),{status:400});const f=[],p=[];for(const k of ['title','description','attachment_path','publish_date','expiry_date'])if(Object.hasOwn(d,k)){f.push(`${k}=?`);p.push(d[k]);}if(f.length){p.push(id);await pool.execute(`UPDATE notices SET ${f.join(',')} WHERE notice_id=?`,p);}return get(id);}
async function remove(id){if(!await get(id))throw nf('Notice not found');await pool.execute('DELETE FROM notices WHERE notice_id=?',[id]);}
module.exports={create,list,listForUser,get,update,remove};
