const { pool }=require('../config/database'); const {hashPassword}=require('./password.service');
function http(status,message){const e=new Error(message);e.status=status;return e;}
const select=`SELECT t.teacher_id,t.user_id,t.employee_code,t.qualification,t.specialization,t.joining_date,t.cnic,t.address,t.salary,t.status,u.full_name,u.email,u.phone,u.username,u.is_active,u.profile_image FROM teachers t JOIN users u ON u.user_id=t.user_id`;
async function getTeacher(id){const [r]=await pool.execute(`${select} WHERE t.teacher_id=?`,[id]);return r[0]||null;} async function getTeacherByUserId(uid){const [r]=await pool.execute(`${select} WHERE t.user_id=?`,[uid]);return r[0]||null;}
async function createTeacher(d){const [role]=await pool.execute('SELECT role_id FROM roles WHERE role_name=? LIMIT 1',['teacher']);if(!role.length)throw http(500,'Teacher role missing from database. Run schema.sql first.');const conn=await pool.getConnection();try{await conn.beginTransaction();const [du]=await conn.execute('SELECT user_id FROM users WHERE username=? OR email=? OR phone=? LIMIT 1',[d.username,d.email,d.phone??null]);if(du.length)throw http(409,'Username, email, or phone already exists');if(d.section_id!=null){const [s]=await conn.execute('SELECT class_teacher_id FROM sections WHERE section_id=?',[d.section_id]);if(!s.length)throw http(404,'Section not found');if(s[0].class_teacher_id!=null)throw http(409,'This section is already assigned to another teacher');}const [u]=await conn.execute('INSERT INTO users(role_id,full_name,email,phone,username,password_hash,is_active) VALUES(?,?,?,?,?,?,1)',[role[0].role_id,d.full_name,d.email,d.phone??null,d.username,await hashPassword(d.password)]);const [t]=await conn.execute('INSERT INTO teachers(user_id,employee_code,qualification,specialization,joining_date,cnic,address,salary) VALUES(?,?,?,?,?,?,?,?)',[u.insertId,d.employee_code??null,d.qualification??null,d.specialization??null,d.joining_date??null,d.cnic??null,d.address??null,d.salary??null]);if(d.section_id!=null)await conn.execute('UPDATE sections SET class_teacher_id=? WHERE section_id=?',[t.insertId,d.section_id]);await conn.commit();return getTeacher(t.insertId);}catch(e){await conn.rollback();if(e.code==='ER_DUP_ENTRY')throw http(409,'Employee code, CNIC, username, email, or phone already exists');throw e;}finally{conn.release();}}
async function listTeachers(q){let sql=select+' WHERE 1=1',p=[];if(q.status)sql+=' AND t.status=?',p.push(q.status);if(q.search){sql+=' AND (u.full_name LIKE ? OR u.email LIKE ?)';const x=`%${q.search}%`;p.push(x,x);}sql+=' ORDER BY u.full_name LIMIT ? OFFSET ?';p.push(Number(q.limit??100),Number(q.skip??0));const[r]=await pool.execute(sql,p);return r;}
async function assignSection(tid,sid){const t=await getTeacher(tid);if(!t)throw http(404,'Teacher not found');const [s]=await pool.execute('SELECT * FROM sections WHERE section_id=?',[sid]);if(!s.length)throw http(404,'Section not found');if(s[0].class_teacher_id!=null&&Number(s[0].class_teacher_id)!==Number(tid))throw http(409,'This section is already assigned to another teacher');const [cur]=await pool.execute('SELECT section_id FROM sections WHERE class_teacher_id=? AND section_id<>?',[tid,sid]);if(cur.length)throw http(409,`This teacher is already assigned to section ${cur[0].section_id}`);await pool.execute('UPDATE sections SET class_teacher_id=? WHERE section_id=?',[tid,sid]);return getSection(tid);}
async function getSection(tid){const[r]=await pool.execute('SELECT t.teacher_id,s.section_id,s.class_id,c.class_name,s.section_name FROM teachers t JOIN sections s ON s.class_teacher_id=t.teacher_id JOIN classes c ON c.class_id=s.class_id WHERE t.teacher_id=?',[tid]);return r[0]||null;}
async function updateTeacher(id,d){const t=await getTeacher(id);if(!t)throw http(404,'Teacher not found');const conn=await pool.getConnection();try{await conn.beginTransaction();if('section_id'in d){if(d.section_id==null){await conn.execute('UPDATE sections SET class_teacher_id=NULL WHERE class_teacher_id=?',[id]);}else{const[s]=await conn.execute('SELECT class_teacher_id FROM sections WHERE section_id=?',[d.section_id]);if(!s.length)throw http(404,'Section not found');if(s[0].class_teacher_id!=null&&Number(s[0].class_teacher_id)!==Number(id))throw http(409,'This section is already assigned to another teacher');await conn.execute('UPDATE sections SET class_teacher_id=NULL WHERE class_teacher_id=? AND section_id<>?',[id,d.section_id]);await conn.execute('UPDATE sections SET class_teacher_id=? WHERE section_id=?',[id,d.section_id]);}}const uf=['full_name','phone','is_active'].filter(k=>k in d),tf=['qualification','specialization','address','salary','status'].filter(k=>k in d);if(uf.length)await conn.execute(`UPDATE users SET ${uf.map(k=>`${k}=?`).join(',')} WHERE user_id=?`,[...uf.map(k=>d[k]),t.user_id]);if(tf.length)await conn.execute(`UPDATE teachers SET ${tf.map(k=>`${k}=?`).join(',')} WHERE teacher_id=?`,[...tf.map(k=>d[k]),id]);await conn.commit();return getTeacher(id);}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function deleteTeacher(id){const t=await getTeacher(id);if(!t)throw http(404,'Teacher not found');await pool.execute('DELETE FROM users WHERE user_id=?',[t.user_id]);}
async function assignments(tid){const [r]=await pool.execute('SELECT assignment_id,teacher_id,subject_id,section_id FROM teacher_subject_assignments WHERE teacher_id=? ORDER BY assignment_id',[tid]);return r;}
async function assignSubject(tid,d){if(!await getTeacher(tid))throw http(404,'Teacher not found');const[s]=await pool.execute('SELECT subject_id,class_id FROM subjects WHERE subject_id=?',[d.subject_id]);if(!s.length)throw http(404,'Subject not found');const[sec]=await pool.execute('SELECT section_id,class_id FROM sections WHERE section_id=?',[d.section_id]);if(!sec.length)throw http(404,'Section not found');if(Number(s[0].class_id)!==Number(sec[0].class_id))throw http(400,'Subject and section belong to different classes');try{const[r]=await pool.execute('INSERT INTO teacher_subject_assignments(teacher_id,subject_id,section_id) VALUES(?,?,?)',[tid,d.subject_id,d.section_id]);return (await pool.execute('SELECT assignment_id,teacher_id,subject_id,section_id FROM teacher_subject_assignments WHERE assignment_id=?',[r.insertId]))[0][0];}catch(e){if(e.code==='ER_DUP_ENTRY')throw http(409,'This subject assignment already exists');throw e;}}
async function removeAssignment(tid,aid){const[r]=await pool.execute('DELETE FROM teacher_subject_assignments WHERE assignment_id=? AND teacher_id=?',[aid,tid]);if(!r.affectedRows)throw http(404,'Assignment not found');}
module.exports={getTeacher,getTeacherByUserId,createTeacher,listTeachers,assignSection,getSection,updateTeacher,deleteTeacher,assignments,assignSubject,removeAssignment};
